spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/board?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user
    password: Welcome1!

  thymeleaf:
    prefix: classpath:/static/
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

  mvc:
    path match:
      matching-strategy: ant_path_matcher